assignment2:                                                                    
	    gcc -o assignment2 assignment2.c -g                                         
		gcc -o child1 child1.c -g                                                   
		gcc -o child2 child2.c -g                                                   
				                                                                                
																								                                                                                
clean:                                                                          
	    rm -f assignment2 child1 child2    


